### ISSUE TITLE
"-d sqlite3" not currently supported by highgroove generator

### ISSUE THREAD

**Issue by jasnow** [bignerdranch/bnr-generator#24]
When you give "sqlite3" as the value of database, then you get multiple errors.

**highgroove new cuc7 --database=sqlite3**
```
         run  rails new cuc7 --skip-bundle -T -q -d sqlite3 from "."
         run  git init -q from "./cuc7"
        gsub  cuc7/Gemfile
        gsub  cuc7/Gemfile
      append  cuc7/Gemfile
         run  rvm 1.9.3-p125 do rvm --rvmrc --create 1.9.3-p125@cuc7 from "./cuc7"
         run  rvm 1.9.3-p125@cuc7 do gem install bundler from "./cuc7"
Successfully installed bundler-1.1.5
1 gem installed
         run  rvm 1.9.3-p125@cuc7 do bundle install --quiet from "./cuc7"
**Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.**

        /Users/whitemac/.rvm/rubies/ruby-1.9.3-p125/bin/ruby extconf.rb --with-sqlite3-include=/Users/whitemac/include --with-sqlite3-lib=/Users/whitemac/lib --with-sqlite3-dir=/Users/whitemac/bin
checking for sqlite3.h... yes
**checking for sqlite3_libversion_number() in -lsqlite3... no**
sqlite3 is missing. Try 'port install sqlite3 +universal'
or 'yum install sqlite-devel' and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
**Could not create Makefile due to some reason, probably lack of**
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/whitemac/.rvm/rubies/ruby-1.9.3-p125/bin/ruby
        --with-sqlite3-dir
        --with-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib=${sqlite3-dir}/lib
        --enable-local
        --disable-local
        --with-sqlite3lib
        --without-sqlite3lib


Gem files will remain installed in /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/sqlite3-1.3.6 for inspection.
Results logged to /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/sqlite3-1.3.6/ext/sqlite3/gem_make.out

**An error occured while installing sqlite3 (1.3.6), and Bundler cannot continue.**
Make sure that `gem install sqlite3 -v '1.3.6'` succeeds before bundling.
         run  rvm 1.9.3-p125@cuc7 do rails g rspec:install from "./cuc7"
/Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:287:in `resolve': Could not find gem 'sqlite3 (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:161:in `start'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:128:in `block in resolve'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:127:in `catch'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:127:in `resolve'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/definition.rb:192:in `resolve'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/definition.rb:127:in `specs'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/environment.rb:27:in `specs'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:41:in `candidate?'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:60:in `setup'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:75:in `<top (required)>'
        from /Users/whitemac/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
        from /Users/whitemac/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /Users/whitemac/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/bin/ruby_noexec_wrapper:9:in `<main>'
         run  rvm 1.9.3-p125@cuc7 do rails g forgery from "./cuc7"
/Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:287:in `resolve': Could not find gem 'sqlite3 (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:161:in `start'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:128:in `block in resolve'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:127:in `catch'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/resolver.rb:127:in `resolve'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/definition.rb:192:in `resolve'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/definition.rb:127:in `specs'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/gems/bundler-1.1.5/lib/bundler/environment.rb:27:in `specs'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:41:in `candidate?'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:60:in `setup'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:75:in `<top (required)>'
        from /Users/whitemac/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
        from /Users/whitemac/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from /Users/whitemac/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p125@cuc7/bin/ruby_noexec_wrapper:9:in `<main>'
      insert  cuc7/spec/spec_helper.rb
/Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/actions/inject_into_file.rb:99:in `binread': No such file or directory - /Users/whitemac/source/cuc7/spec/spec_helper.rb (Errno::ENOENT)
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/actions/inject_into_file.rb:99:in `replace!'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/actions/inject_into_file.rb:60:in `invoke!'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/actions.rb:95:in `action'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/actions/inject_into_file.rb:31:in `insert_into_file'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/highgroove_generator-0.4.0/lib/highgroove_command.rb:44:in `block in new'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/actions.rb:182:in `block in inside'
        from /Users/whitemac/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:125:in `chdir'
        from /Users/whitemac/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/fileutils.rb:125:in `cd'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/actions.rb:182:in `inside'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/highgroove_generator-0.4.0/lib/highgroove_command.rb:15:in `new'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/task.rb:27:in `run'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/invocation.rb:120:in `invoke_task'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor.rb:275:in `dispatch'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.15.4/lib/thor/base.rb:425:in `start'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/gems/highgroove_generator-0.4.0/bin/highgroove:4:in `<top (required)>'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/bin/highgroove:23:in `load'
        from /Users/whitemac/.rvm/gems/ruby-1.9.3-p194/bin/highgroove:23:in `<main>'
```
EOF

**Comment by jasnow** [comment]
Old issue, so closing.
